### ISSUE TITLE
VSync limiting framerate

### ISSUE THREAD

**Issue by KarboXXX** [nmakel/i3-gnome#3]
When playing games, the framerate is always 60fps (60hz) and sometimes it goes up to 100fps, but either cases gives me extreme input lag. It does not happen on neither gnome nor i3 by default.

Using i3 with compton with vsync doesn't happen either.

compton.conf:
```
backend = "glx";
vsync = "opengl-swc";
```

uname -a
```
Linux karbox 5.13.0-52-generic #59~20.04.1-Ubuntu SMP Thu Jun 16 21:21:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by nmakel** [comment]
Using compton fixes the issue?

**Comment by renangiuliasse** [comment]
No, i have to choose between input lag or screen tearing

**Comment by nmakel** [comment]
So... this sounds like an X11/graphics driver issue. Enabling vsync should cap your fps to whatever refresh rate your monitor is set to. Have you tried disabling vsync?

**Comment by renangiuliasse** [comment]
Yes, without compton there's tearing, but not as much as compton without vsync, and with compton without vsync it uses almost 17% CPU doing nothing

Editing X11 settings with 20-intel.conf to enable TearFree there's no tearing, no high cpu usage, and less input lag, and makes compton use more CPU normally
